# -*- coding: utf-8 -*-
"""calculadora_drawdonw_ruina.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WyS-7JHofVnm-m-qmEsHEmgQjt9dbA4
"""

import streamlit as st

def calculate_drawdown(pico, vale):
    dd = (vale - pico) / pico
    return dd

def calculate_ruin_risk(drawdown, win_rate, bet_size):
    ruin_risk = (1 - win_rate) / (win_rate * (1 + drawdown / bet_size))
    return ruin_risk

def main():
    st.title("Calculadora de Drawdown e Risco de Ruína")

    pico = st.number_input("Valor do Pico:")
    vale = st.number_input("Valor do Vale:")
    win_rate = st.number_input("Taxa de Vitória (%):", min_value=0.0, max_value=100.0, value=50.0)
    bet_size = st.number_input("Tamanho da Aposta:", min_value=0.01, step=0.01, value=1.0)

    drawdown = calculate_drawdown(pico, vale)
    drawdown_percentage = round(drawdown * 100, 2)
    st.write("Drawdown: {}%".format(drawdown_percentage))

    ruin_risk = calculate_ruin_risk(drawdown, win_rate/100, bet_size)
    ruin_risk_percentage = ruin_risk * 100
    st.write("Risco de Ruína: {}%".format(ruin_risk_percentage))

if __name__ == '__main__':
    main()